// generated by scripts/new-module.mjs; edit freely
import { readdirSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { PGlite } from '@electric-sql/pglite'
import type { Queryable } from '@nabvy/db'
import { drizzle } from 'drizzle-orm/pglite'

// An in-process Postgres (PGlite) with Supabase's stand-in roles (anon, authenticated: this
// module's migration revokes from them, as listing-suppression's does), then core, audit-log,
// switches, listing-ingest, detail-evidence, listing-lifecycle, listing-suppression,
// quote-redaction and listing-card (packages/db/README.md): every dependency the module card
// names, so app.v_listing_card can be built and queried for real. PGlite has no PostGIS, pgvector
// or pg_trgm; skip them here unless this module needs one. The full migration set runs on real
// Postgres in `pnpm db:dry-run` (packages/db/tests/listing-card.test.sql).

const root = fileURLToPath(new URL('../../../../', import.meta.url))
const migrations = join(root, 'packages/db/migrations')
const SUPABASE_STUBS = join(root, 'supabase/tests/supabase-stubs.sql')

function migrationFiles(module: string): string[] {
  const dir = join(migrations, module)
  return readdirSync(dir)
    .filter((name) => /^\d{14}_.+\.sql$/.test(name))
    .sort()
    .map((name) => join(dir, name))
}

export type Role = 'postgres' | 'nabvy_app' | 'nabvy_pipeline'

export interface TestDatabase {
  pg: PGlite
  /**
   * Runs `fn` in one transaction as `role`; with `userId`, as withUser does (app.user_id set
   * locally). The transaction commits unless `fn` throws.
   */
  as<T>(role: Role, fn: (tx: Queryable) => Promise<T>, userId?: string): Promise<T>
  /** Runs SQL as the migration superuser. */
  sql(query: string, params?: unknown[]): Promise<Record<string, unknown>[]>
  close(): Promise<void>
}

export async function createTestDatabase(): Promise<TestDatabase> {
  const pg = new PGlite()
  for (const file of [
    SUPABASE_STUBS,
    ...migrationFiles('core'),
    ...migrationFiles('audit-log'),
    ...migrationFiles('switches'),
    ...migrationFiles('listing-ingest'),
    ...migrationFiles('detail-evidence'),
    ...migrationFiles('listing-lifecycle'),
    ...migrationFiles('listing-suppression'),
    ...migrationFiles('quote-redaction'),
    ...migrationFiles('listing-card'),
  ]) {
    const text = readFileSync(file, 'utf8')
      .split('\n')
      .filter((line) => !/^create extension /i.test(line))
      .join('\n')
      .replaceAll('--> statement-breakpoint', '')
    await pg.exec(text)
  }
  const db = drizzle(pg)
  return {
    pg,
    async as(role, fn, userId) {
      return db.transaction(async (tx) => {
        if (role !== 'postgres') await tx.execute(`set local role ${role}`)
        if (userId) await tx.execute(`select set_config('app.user_id', '${userId}', true)`)
        return fn(tx as unknown as Queryable)
      })
    },
    async sql(query, params = []) {
      return (await pg.query<Record<string, unknown>>(query, params)).rows
    },
    close: () => pg.close(),
  }
}

/** Sets this module's switch, as the migration superuser (mirrors an admin change). */
export async function setSwitch(db: TestDatabase, state: 'off' | 'shadow' | 'on'): Promise<void> {
  await setModuleSwitch(db, 'listing-card', state)
}

/** Sets any module's switch: the fixtures need listing-card's dependencies switched on too. */
export async function setModuleSwitch(
  db: TestDatabase,
  name: string,
  state: 'off' | 'shadow' | 'on',
): Promise<void> {
  await db.sql(
    `insert into switches.switches (name, kind, state) values ($1, 'module', $2)
     on conflict (name) do update set state = excluded.state`,
    [name, state],
  )
}
