import { z } from 'zod'

/**
 * Any RFC 9562 UUID. Row IDs are generated by the database (`nabvy_core.uuidv7()`), so a schema
 * that reads one back should accept any version; Better Auth's user IDs are version 4.
 */
export const Uuid = z.uuid()
export type Uuid = z.infer<typeof Uuid>

/** A UUID version 7: time-ordered. Event IDs and every ID Nabvy generates itself. */
export const UuidV7 = z.uuid({ version: 'v7' })
export type UuidV7 = z.infer<typeof UuidV7>

/**
 * A UUID branded with the entity it identifies, so a `HuntId` cannot be passed where an
 * `AlertId` is expected. Modules declare their own: `export const HuntId = brandedId('HuntId')`.
 */
export function brandedId<const B extends string>(_brand: B) {
  return Uuid.brand<B>()
}

/** Generates a UUID v7 (RFC 9562 §5.7) from the clock and a CSPRNG. */
export function uuidv7(now: number = Date.now()): UuidV7 {
  const bytes = new Uint8Array(16)
  crypto.getRandomValues(bytes)
  let ms = Math.floor(now)
  for (let i = 5; i >= 0; i--) {
    bytes[i] = ms % 256
    ms = Math.floor(ms / 256)
  }
  bytes[6] = ((bytes[6] ?? 0) & 0x0f) | 0x70
  bytes[8] = ((bytes[8] ?? 0) & 0x3f) | 0x80
  const hex = Array.from(bytes, (b) => b.toString(16).padStart(2, '0')).join('')
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`
}
