// generated by scripts/new-module.mjs; edit freely
// Drizzle Kit configuration for the want-manager module's migrations. Paths are relative to
// packages/db, where `pnpm db:generate want-manager` runs. See packages/db/README.md.
import { defineConfig } from 'drizzle-kit'

export default defineConfig({
  dialect: 'postgresql',
  schema: './src/schema/want-manager.ts',
  out: './migrations/want-manager',
  schemaFilter: ['want_manager'],
  migrations: { prefix: 'supabase' },
})
