// Used only by `pnpm auth:generate` to generate the Better Auth tables (src/schema/better-auth.ts).
// It lists the plugins that add tables or fields, per docs/decisions.md ("Authentication and
// authorisation"): magic link, Google sign-in, admin, captcha (Turnstile) and Stripe. The running
// configuration belongs to the auth module (task 4.0); keep the plugin list in step with it and
// regenerate when it changes. No secrets: generation never calls a provider.
import { stripe } from '@better-auth/stripe'
import { betterAuth } from 'better-auth'
import { drizzleAdapter } from 'better-auth/adapters/drizzle'
import { admin, captcha, magicLink } from 'better-auth/plugins'
import Stripe from 'stripe'

const unused = 'generation-only'

export const auth = betterAuth({
  baseURL: 'http://localhost:3000',
  database: drizzleAdapter({} as never, { provider: 'pg' }),
  // User IDs are UUIDs generated by the database (docs/contracts.md, "Identity").
  advanced: { database: { generateId: 'uuid' } },
  socialProviders: { google: { clientId: unused, clientSecret: unused } },
  plugins: [
    magicLink({ sendMagicLink: async () => {} }),
    admin(),
    captcha({ provider: 'cloudflare-turnstile', secretKey: unused }),
    stripe({
      stripeClient: new Stripe(unused),
      stripeWebhookSecret: unused,
      subscription: { enabled: true, plans: [] },
    }),
  ],
})
