-- Better Auth tables: ownership, access and the founder seed. Hand-written (drizzle-kit --custom).
comment on schema better_auth is
  'Better Auth tables, generated by its CLI (pnpm auth:generate). Owner: the auth module. Internal; not exposed to the Data API.';
revoke all on schema better_auth from public;

-- No application role is granted these tables yet. Better Auth reads sessions and accounts
-- before any user is known, so they cannot sit behind the withUser policy; which role the running
-- Better Auth instance connects as is task 4.0's decision (docs/questions.md). Until then nothing
-- but the migration role can read them.

-- Keep updated_at current for rows written outside Better Auth (the seed below, admin tools).
select nabvy_core.track_updated_at('better_auth.user');

-- Founder seed (docs/engineering.md, "Admin bootstrap"). Creates each ADMIN_EMAILS address as an
-- admin user, or promotes it if it exists; idempotent. The name is left empty: the founder sets
-- it on first sign-in. Called by `pnpm db:seed`. Returns how many rows it inserted or changed.
-- The audit_log row the bootstrap calls for arrives with the ops-monitor module.
create or replace function better_auth.seed_founders(emails text[]) returns integer
language plpgsql
set search_path = pg_catalog
as $$
declare
  changed integer;
begin
  if emails is null or cardinality(emails) = 0 then
    raise exception 'seed_founders: ADMIN_EMAILS is empty';
  end if;
  insert into better_auth."user" (name, email, email_verified, role)
  select '', address, false, 'admin'
  from (select distinct lower(trim(e)) as address from unnest(emails) as e) as addresses
  where address <> ''
  on conflict (email) do update
    set role = 'admin'
    where better_auth."user".role is distinct from 'admin';
  get diagnostics changed = row_count;
  return changed;
end;
$$;
revoke all on function better_auth.seed_founders(text[]) from public;
