// generated by scripts/new-module.mjs; edit freely
import { readdirSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { PGlite } from '@electric-sql/pglite'
import { pg_trgm } from '@electric-sql/pglite/contrib/pg_trgm'
import type { Queryable } from '@nabvy/db'
import { drizzle } from 'drizzle-orm/pglite'

// An in-process Postgres (PGlite) with the real migrations of every module lookup() touches:
// core, audit-log, switches, better-auth (account.isActive), usage-ledger (chargeUsage),
// scan-recognition (v_scans) and asking-price-index (v_groups), plus scan-lookup itself
// (packages/db/README.md), so the tests exercise the actual tables, grants, policies and
// triggers. PGlite has no PostGIS, pgvector or pg_trgm; skip them here unless this module needs
// one. The full migration set runs on real Postgres in `pnpm db:dry-run`
// (packages/db/tests/scan-lookup.test.sql).

const migrations = fileURLToPath(new URL('../../../../packages/db/migrations/', import.meta.url))

function migrationFiles(module: string): string[] {
  const dir = join(migrations, module)
  return readdirSync(dir)
    .filter((name) => /^\d{14}_.+\.sql$/.test(name))
    .sort()
    .map((name) => join(dir, name))
}

export type Role = 'postgres' | 'nabvy_app' | 'nabvy_pipeline'

export interface TestDatabase {
  pg: PGlite
  /**
   * Runs `fn` in one transaction as `role`; with `userId`, as withUser does (app.user_id set
   * locally). The transaction commits unless `fn` throws.
   */
  as<T>(role: Role, fn: (tx: Queryable) => Promise<T>, userId?: string): Promise<T>
  /** Runs SQL as the migration superuser. */
  sql(query: string, params?: unknown[]): Promise<Record<string, unknown>[]>
  close(): Promise<void>
}

export async function createTestDatabase(): Promise<TestDatabase> {
  const pg = new PGlite({ extensions: { pg_trgm } })
  // Supabase's Data API roles: real Postgres always has them, but a fresh PGlite does not, and
  // asking-price-index's access migration revokes from them. Created once, up front, so every
  // module's access migration below can assume they exist (as it can on the live project).
  await pg.exec(`create role anon nologin; create role authenticated nologin;`)
  for (const file of [
    ...migrationFiles('core'),
    ...migrationFiles('audit-log'),
    ...migrationFiles('switches'),
    ...migrationFiles('better-auth'),
    ...migrationFiles('usage-ledger'),
    ...migrationFiles('scan-recognition'),
    ...migrationFiles('asking-price-index'),
    ...migrationFiles('scan-lookup'),
  ]) {
    const text = readFileSync(file, 'utf8')
      .split('\n')
      .filter((line) => !/^create extension /i.test(line))
      .join('\n')
      .replaceAll('--> statement-breakpoint', '')
    await pg.exec(text)
  }
  const db = drizzle(pg)
  return {
    pg,
    async as(role, fn, userId) {
      return db.transaction(async (tx) => {
        if (role !== 'postgres') await tx.execute(`set local role ${role}`)
        if (userId) await tx.execute(`select set_config('app.user_id', '${userId}', true)`)
        return fn(tx as unknown as Queryable)
      })
    },
    async sql(query, params = []) {
      return (await pg.query<Record<string, unknown>>(query, params)).rows
    },
    close: () => pg.close(),
  }
}

/** Sets a module's switch, as the migration superuser (mirrors an admin change). */
export async function setSwitch(
  db: TestDatabase,
  state: 'off' | 'shadow' | 'on',
  name = 'scan-lookup',
): Promise<void> {
  await db.sql(
    `insert into switches.switches (name, kind, state) values ($2, 'module', $1)
     on conflict (name) do update set state = excluded.state`,
    [state, name],
  )
}

/**
 * Turns on every module `lookup()` reads through: scan-lookup itself, scan-recognition and
 * asking-price-index (their views hide rows while off, rule 11) and usage-ledger (chargeUsage
 * refuses while off).
 */
export async function setAllOn(db: TestDatabase): Promise<void> {
  for (const name of ['scan-lookup', 'scan-recognition', 'asking-price-index', 'usage-ledger']) {
    await setSwitch(db, 'on', name)
  }
}

/** A user active enough for `account.isActive` to read true (better_auth.user, not banned). */
export async function seedUser(db: TestDatabase, userId: string): Promise<void> {
  await db.sql(`insert into better_auth."user" (id, name, email) values ($1, 'Test', $2)`, [
    userId,
    `${userId}@example.test`,
  ])
}

/** Enough top-up credit for `chargeUsage` to succeed. */
export async function seedCredits(
  db: TestDatabase,
  userId: string,
  credits: number,
): Promise<void> {
  await db.sql(
    `insert into usage_ledger.entries (user_id, kind, credits, ref_id) values ($1, 'topup', $2, 'seed')`,
    [userId, credits],
  )
}

/** An identified scan-recognition scan, ready for `lookup()` to price. */
export async function seedScan(
  db: TestDatabase,
  scanId: string,
  userId: string,
  catalogueId: string,
): Promise<void> {
  await db.sql(
    `insert into scan_recognition.scan_events
       (id, user_id, method, status, identified, candidates, confidence, at, identified_at)
     values ($1, $2, 'vision', 'identified', $3, array[$3], 1, now(), now())`,
    [scanId, userId, catalogueId],
  )
}

/** One asking-price-index group and its figures, in the beta's country and currency. */
export async function seedGroup(
  db: TestDatabase,
  groupKey: string,
  catalogueId: string,
  figures: { n: number; median: number; p25: number; p75: number },
  overrides: { context?: string; condition?: string; country?: string; currency?: string } = {},
): Promise<void> {
  const context = overrides.context ?? 'standalone'
  const condition = overrides.condition ?? 'used_good'
  const country = overrides.country ?? 'GB'
  const currency = overrides.currency ?? 'GBP'
  await db.sql(
    `insert into asking_price_index.groups
       (group_key, catalogue_id, context, condition, country, currency, window_days, label)
     values ($1, $2, $3, $4, $5, $6, 30, $2)`,
    [groupKey, catalogueId, context, condition, country, currency],
  )
  await db.sql(
    `insert into asking_price_index.stats
       (group_key, n, median, mad, p25, p75, min, max, thin, copy_collapse, as_of)
     values ($1, $2, $3, 0, $4, $5, $4, $5, false, false, now())`,
    [groupKey, figures.n, figures.median, figures.p25, figures.p75],
  )
}
