// generated by scripts/new-module.mjs; edit freely
import { readdirSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { PGlite } from '@electric-sql/pglite'
import { pg_trgm } from '@electric-sql/pglite/contrib/pg_trgm'
import type { Queryable } from '@nabvy/db'
import { drizzle } from 'drizzle-orm/pglite'

// An in-process Postgres (PGlite) with the migrations of this module and of every module it reads
// applied (packages/db/README.md), so the tests exercise the actual tables, grants, policies and
// triggers. Add another module's migrations here (for example better-auth, for an account check)
// once this module reads its tables or functions. PGlite has no PostGIS, pgvector or pg_trgm; skip
// them here unless this module needs one. The full migration set runs on real Postgres in
// `pnpm db:dry-run` (packages/db/tests/asking-price-index.test.sql).

export const READ_MODULES = [
  'listing-ingest',
  'detail-evidence',
  'parts-record',
  'listing-assessment',
  'noise-filter',
  'city-pages',
  'relist-merge',
  'copy-advert',
  'product-catalogue',
  'listing-suppression',
]

const migrations = fileURLToPath(new URL('../../../../packages/db/migrations/', import.meta.url))

const root = fileURLToPath(new URL('../../../../', import.meta.url))

function migrationFiles(module: string): string[] {
  return sqlIn(join(migrations, module))
}

function sqlIn(dir: string): string[] {
  return readdirSync(dir)
    .filter((name) => /^\d{14}_.+\.sql$/.test(name))
    .sort()
    .map((name) => join(dir, name))
}

/** Modules in dependency order (module.json `dependsOn`), ending with `targets`. */
function ordered(targets: string[]): string[] {
  const out: string[] = []
  const visit = (module: string) => {
    if (out.includes(module)) return
    const meta = join(migrations, module, 'module.json')
    const deps: string[] =
      module === 'core' ? [] : JSON.parse(readFileSync(meta, 'utf8')).dependsOn ?? ['core']
    for (const dep of deps) visit(dep)
    out.push(module)
  }
  for (const target of targets) visit(target)
  return out
}

export type Role = 'postgres' | 'nabvy_app' | 'nabvy_pipeline'

export interface TestDatabase {
  pg: PGlite
  /**
   * Runs `fn` in one transaction as `role`; with `userId`, as withUser does (app.user_id set
   * locally). The transaction commits unless `fn` throws.
   */
  as<T>(role: Role, fn: (tx: Queryable) => Promise<T>, userId?: string): Promise<T>
  /** Runs SQL as the migration superuser. */
  sql(query: string, params?: unknown[]): Promise<Record<string, unknown>[]>
  close(): Promise<void>
}

export async function createTestDatabase(): Promise<TestDatabase> {
  // copy-advert's access migration builds a pg_trgm index, so pg_trgm is loaded (as in
  // copy-advert's tests) and its `create extension` line kept.
  const pg = new PGlite({ extensions: { pg_trgm } })
  await pg.exec('set search_path = "$user", public, extensions')
  // Every module whose views the index reads, so the tests run its real cross-module SQL.
  // The Supabase stand-ins and the gateway bootstrap come first, as in listing-ingest's tests.
  for (const file of [
    join(root, 'supabase/tests/supabase-stubs.sql'),
    ...sqlIn(join(root, 'supabase/migrations')),
    ...ordered(['audit-log', 'asking-price-index', ...READ_MODULES]).flatMap(migrationFiles),
  ]) {
    const text = readFileSync(file, 'utf8')
      .split('\n')
      .filter((line) => !/^create extension /i.test(line) || /pg_trgm/i.test(line))
      .join('\n')
      .replaceAll('--> statement-breakpoint', '')
    await pg.exec(text)
  }
  const db = drizzle(pg)
  return {
    pg,
    async as(role, fn, userId) {
      return db.transaction(async (tx) => {
        if (role !== 'postgres') await tx.execute(`set local role ${role}`)
        if (userId) await tx.execute(`select set_config('app.user_id', '${userId}', true)`)
        return fn(tx as unknown as Queryable)
      })
    },
    async sql(query, params = []) {
      return (await pg.query<Record<string, unknown>>(query, params)).rows
    },
    close: () => pg.close(),
  }
}

/** Sets this module's switch, as the migration superuser (mirrors an admin change). */
export async function setSwitch(
  db: TestDatabase,
  state: 'off' | 'shadow' | 'on',
  name = 'asking-price-index',
): Promise<void> {
  await db.sql(
    `insert into switches.switches (name, kind, state) values ($2, 'module', $1)
     on conflict (name) do update set state = excluded.state`,
    [state, name],
  )
}
