// generated by scripts/new-module.mjs; edit freely
// Drizzle Kit configuration for the details-selector module's migrations. Paths are relative to
// packages/db, where `pnpm db:generate details-selector` runs. See packages/db/README.md.
import { defineConfig } from 'drizzle-kit'

export default defineConfig({
  dialect: 'postgresql',
  schema: './src/schema/details-selector.ts',
  out: './migrations/details-selector',
  schemaFilter: ['details_selector'],
  migrations: { prefix: 'supabase' },
})
