// generated by scripts/new-module.mjs; edit freely
// Drizzle Kit configuration for the pickup-location module's migrations. Paths are relative to
// packages/db, where `pnpm db:generate pickup-location` runs. See packages/db/README.md.
import { defineConfig } from 'drizzle-kit'

export default defineConfig({
  dialect: 'postgresql',
  schema: './src/schema/pickup-location.ts',
  out: './migrations/pickup-location',
  schemaFilter: ['pickup_location'],
  migrations: { prefix: 'supabase' },
})
