// generated by scripts/new-module.mjs; edit freely
// Drizzle Kit configuration for the suspected-labels module's migrations. Paths are relative to
// packages/db, where `pnpm db:generate suspected-labels` runs. See packages/db/README.md.
import { defineConfig } from 'drizzle-kit'

export default defineConfig({
  dialect: 'postgresql',
  schema: './src/schema/suspected-labels.ts',
  out: './migrations/suspected-labels',
  schemaFilter: ['suspected_labels'],
  migrations: { prefix: 'supabase' },
})
