import { ACCOUNT_RESTRICTED_MESSAGE } from '@nabvy/contracts/modules/auth'
import { account, session, user, verification } from '@nabvy/db/schema/better-auth'
import { type BetterAuthPlugin, betterAuth } from 'better-auth'
import { drizzleAdapter } from 'better-auth/adapters/drizzle'
import { APIError } from 'better-auth/api'
import { admin, captcha, magicLink } from 'better-auth/plugins'
import { isFounderEmail } from './domain/founders'
import type { MagicLinkSender } from './email/magic-link'

/** A Drizzle Postgres database, as the Drizzle adapter takes it (node-postgres in production). */
export type AuthDatabase = Parameters<typeof drizzleAdapter>[0]

export interface AuthOptions {
  /** Drizzle on DATABASE_URL_AUTH, connected as nabvy_auth (README.md, "Database role"). */
  db: AuthDatabase
  /** BETTER_AUTH_URL: the app's public origin. */
  baseURL: string
  /** BETTER_AUTH_SECRET: signs cookies and tokens. */
  secret: string
  /** ADMIN_EMAILS: founder addresses that receive the admin role on sign-in. */
  adminEmails: readonly string[]
  magicLinkSender: MagicLinkSender
  /** Cloudflare Turnstile on magic-link requests. Required: sign-up spends the free tier. */
  turnstile: { secretKey: string; siteVerifyURL?: string }
  /** Google sign-in, when its OAuth client exists (docs/questions.md). */
  google?: { clientId: string; clientSecret: string }
  /** Silences Better Auth's logger (tests). */
  quiet?: boolean
}

// Sessions: database-backed, 30-day expiry, five-minute cookie cache (docs/security.md). The
// session helpers bypass the cookie cache, so a revoked session or a new restriction takes effect
// on the next request.
const SESSION_EXPIRES_IN = 60 * 60 * 24 * 30
const SESSION_UPDATE_AGE = 60 * 60 * 24
const COOKIE_CACHE_MAX_AGE = 60 * 5
const MAGIC_LINK_EXPIRES_IN = 60 * 5

/**
 * Keeps Better Auth's `banReason` out of every API response (session, sign-in, admin lists):
 * the reason behind a restriction stays internal (docs/decisions.md, "Fair use, suspension and
 * bans"). Later plugins' field definitions override earlier ones, so this runs after `admin`.
 * The column is still read and written.
 */
const privateBanReason = {
  id: 'nabvy-private-ban-reason',
  schema: {
    user: {
      fields: {
        banReason: { type: 'string', required: false, input: false, returned: false },
      },
    },
  },
} satisfies BetterAuthPlugin

/** The Better Auth server instance (docs/decisions.md, "Authentication and authorisation"). */
export function createAuth(options: AuthOptions) {
  const founder = (email: string) => isFounderEmail(email, options.adminEmails)
  return betterAuth({
    baseURL: options.baseURL,
    secret: options.secret,
    basePath: '/api/auth',
    database: drizzleAdapter(options.db, {
      provider: 'pg',
      schema: { user, session, account, verification },
    }),
    // User IDs are UUIDs generated by the database (docs/contracts.md, "Identity").
    advanced: { database: { generateId: 'uuid' } },
    telemetry: { enabled: false },
    ...(options.quiet ? { logger: { disabled: true } } : {}),
    session: {
      expiresIn: SESSION_EXPIRES_IN,
      updateAge: SESSION_UPDATE_AGE,
      cookieCache: { enabled: true, maxAge: COOKIE_CACHE_MAX_AGE },
    },
    // No passwords: magic link and Google only.
    emailAndPassword: { enabled: false },
    ...(options.google
      ? {
          socialProviders: {
            google: {
              clientId: options.google.clientId,
              clientSecret: options.google.clientSecret,
            },
          },
        }
      : {}),
    databaseHooks: {
      user: {
        create: {
          // Founder bootstrap for new accounts.
          async before(data) {
            return founder(data.email) ? { data: { ...data, role: 'admin' } } : undefined
          },
        },
      },
      session: {
        create: {
          // Email verification is required before any session exists. A magic link proves the
          // address; Google's verified-email claim sets it for Google sign-in. Also promotes an
          // existing account whose address is in ADMIN_EMAILS (founder bootstrap).
          async before(data, ctx) {
            if (!ctx) return false
            const owner = await ctx.context.internalAdapter.findUserById(data.userId)
            if (!owner?.emailVerified) {
              throw APIError.from('FORBIDDEN', {
                code: 'EMAIL_NOT_VERIFIED',
                message: 'Verify your email address to sign in.',
              })
            }
            if (founder(owner.email) && (owner as { role?: string | null }).role !== 'admin') {
              await ctx.context.internalAdapter.updateUser(owner.id, { role: 'admin' })
            }
            return undefined
          },
        },
      },
    },
    plugins: [
      magicLink({
        expiresIn: MAGIC_LINK_EXPIRES_IN,
        storeToken: 'hashed',
        sendMagicLink: async ({ email, url }) => {
          await options.magicLinkSender.send({ email, url })
        },
      }),
      admin({
        defaultRole: 'user',
        adminRoles: ['admin'],
        // Shown when a restricted account tries to sign in: the vague notice only.
        bannedUserMessage: ACCOUNT_RESTRICTED_MESSAGE,
      }),
      privateBanReason,
      captcha({
        provider: 'cloudflare-turnstile',
        secretKey: options.turnstile.secretKey,
        ...(options.turnstile.siteVerifyURL
          ? { siteVerifyURLOverride: options.turnstile.siteVerifyURL }
          : {}),
        // A magic-link request is also the sign-up (docs/security.md).
        endpoints: ['/sign-in/magic-link'],
      }),
    ],
  })
}

export type Auth = ReturnType<typeof createAuth>
