import { sql } from 'drizzle-orm'
import { pgSchema, timestamp, uuid } from 'drizzle-orm/pg-core'

/**
 * Helpers for module schema files (src/schema/<module>.ts). Each module owns one Postgres schema
 * named after it in snake case (`listing-registry` → `listing_registry`); README.md has the rules.
 */

/** Postgres schemas a module may never be named after: Supabase's own and Nabvy's core. */
export const RESERVED_SCHEMAS = new Set([
  'public',
  'auth',
  'storage',
  'realtime',
  'extensions',
  'graphql',
  'graphql_public',
  'vault',
  'net',
  'cron',
  'pgmq',
  'pgsodium',
  'supabase_functions',
  'supabase_migrations',
  'information_schema',
  'nabvy_core',
  'apify_gateway',
  'marketplace_monitor',
])

const MODULE_NAME = /^[a-z][a-z0-9]*(-[a-z0-9]+)*$/

export function schemaNameOf(module: string): string {
  if (!MODULE_NAME.test(module)) throw new Error(`Module name "${module}" must be kebab case`)
  const schema = module.replaceAll('-', '_')
  if (RESERVED_SCHEMAS.has(schema) || schema.startsWith('pg_')) {
    throw new Error(`Module name "${module}" maps to the reserved schema "${schema}"`)
  }
  return schema
}

/** The module's own Postgres schema: `export const schema = moduleSchema('hunt-manager')`. */
export function moduleSchema(module: string) {
  return pgSchema(schemaNameOf(module))
}

/** Primary key generated by the database as a UUID v7. */
export const idColumn = () => uuid('id').primaryKey().default(sql`nabvy_core.uuidv7()`)

/**
 * `created_at` and `updated_at`. `updated_at` is maintained by the `nabvy_core.set_updated_at`
 * trigger, which the module's RLS migration attaches (README.md, "Every table").
 */
export const timestampColumns = () => ({
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
})
