// generated by scripts/new-module.mjs; edit freely
// Drizzle Kit configuration for the copy-advert module's migrations. Paths are relative to
// packages/db, where `pnpm db:generate copy-advert` runs. See packages/db/README.md.
import { defineConfig } from 'drizzle-kit'

export default defineConfig({
  dialect: 'postgresql',
  schema: './src/schema/copy-advert.ts',
  out: './migrations/copy-advert',
  schemaFilter: ['copy_advert'],
  migrations: { prefix: 'supabase' },
})
