// generated by scripts/new-module.mjs; edit freely
// Event handlers. Each takes a batch (100-500 items), is idempotent (key
// source + sourceListingId + contentHash, or the natural id + version) and stamps its
// T-timestamps (CLAUDE.md; _rules.md rules 8-10).
export {}
