// generated by scripts/new-module.mjs; edit freely
// Drizzle Kit configuration for the pasted-link-lookup module's migrations. Paths are relative to
// packages/db, where `pnpm db:generate pasted-link-lookup` runs. See packages/db/README.md.
import { defineConfig } from 'drizzle-kit'

export default defineConfig({
  dialect: 'postgresql',
  schema: './src/schema/pasted-link-lookup.ts',
  out: './migrations/pasted-link-lookup',
  schemaFilter: ['pasted_link_lookup'],
  migrations: { prefix: 'supabase' },
})
