// generated by scripts/new-module.mjs; edit freely
// Drizzle Kit configuration for the listing-card module's migrations. Paths are relative to
// packages/db, where `pnpm db:generate listing-card` runs. See packages/db/README.md.
import { defineConfig } from 'drizzle-kit'

export default defineConfig({
  dialect: 'postgresql',
  schema: './src/schema/listing-card.ts',
  out: './migrations/listing-card',
  schemaFilter: ['listing_card'],
  migrations: { prefix: 'supabase' },
})
