// generated by scripts/new-module.mjs; edit freely
// Drizzle Kit configuration for the router-gateway module's migrations. Paths are relative to
// packages/db, where `pnpm db:generate router-gateway` runs. See packages/db/README.md.
import { defineConfig } from 'drizzle-kit'

export default defineConfig({
  dialect: 'postgresql',
  schema: './src/schema/router-gateway.ts',
  out: './migrations/router-gateway',
  schemaFilter: ['router_gateway'],
  migrations: { prefix: 'supabase' },
})
