// generated by scripts/new-module.mjs; edit freely
// Drizzle Kit configuration for the scan-lookup module's migrations. Paths are relative to
// packages/db, where `pnpm db:generate scan-lookup` runs. See packages/db/README.md.
import { defineConfig } from 'drizzle-kit'

export default defineConfig({
  dialect: 'postgresql',
  schema: './src/schema/scan-lookup.ts',
  out: './migrations/scan-lookup',
  schemaFilter: ['scan_lookup'],
  migrations: { prefix: 'supabase' },
})
