// generated by scripts/new-module.mjs; edit freely
// Drizzle Kit configuration for the demand-signals module's migrations. Paths are relative to
// packages/db, where `pnpm db:generate demand-signals` runs. See packages/db/README.md.
import { defineConfig } from 'drizzle-kit'

export default defineConfig({
  dialect: 'postgresql',
  schema: './src/schema/demand-signals.ts',
  out: './migrations/demand-signals',
  schemaFilter: ['demand_signals'],
  migrations: { prefix: 'supabase' },
})
