// generated by scripts/new-module.mjs; edit freely
// Drizzle Kit configuration for the check-scheduler module's migrations. Paths are relative to
// packages/db, where `pnpm db:generate check-scheduler` runs. See packages/db/README.md.
import { defineConfig } from 'drizzle-kit'

export default defineConfig({
  dialect: 'postgresql',
  schema: './src/schema/check-scheduler.ts',
  out: './migrations/check-scheduler',
  schemaFilter: ['check_scheduler'],
  migrations: { prefix: 'supabase' },
})
