// generated by scripts/new-module.mjs; edit freely
// Drizzle Kit configuration for the parts-record module's migrations. Paths are relative to
// packages/db, where `pnpm db:generate parts-record` runs. See packages/db/README.md.
import { defineConfig } from 'drizzle-kit'

export default defineConfig({
  dialect: 'postgresql',
  schema: './src/schema/parts-record.ts',
  out: './migrations/parts-record',
  schemaFilter: ['parts_record'],
  migrations: { prefix: 'supabase' },
})
