// generated by scripts/new-module.mjs; edit freely
import { readdirSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { PGlite } from '@electric-sql/pglite'
import type { Queryable } from '@nabvy/db'
import { drizzle } from 'drizzle-orm/pglite'

// An in-process Postgres (PGlite) with the core, audit-log, switches and router-gateway migrations
// applied (packages/db/README.md), so the tests exercise the actual tables, grants, policies and
// triggers. Add another module's migrations here (for example better-auth, for an account check)
// once this module reads its tables or functions. PGlite has no PostGIS, pgvector or pg_trgm; skip
// them here unless this module needs one. The full migration set runs on real Postgres in
// `pnpm db:dry-run` (packages/db/tests/router-gateway.test.sql).

const migrations = fileURLToPath(new URL('../../../../packages/db/migrations/', import.meta.url))

function migrationFiles(module: string): string[] {
  const dir = join(migrations, module)
  return readdirSync(dir)
    .filter((name) => /^\d{14}_.+\.sql$/.test(name))
    .sort()
    .map((name) => join(dir, name))
}

export type Role = 'postgres' | 'nabvy_app' | 'nabvy_pipeline'

export interface TestDatabase {
  pg: PGlite
  /**
   * Runs `fn` in one transaction as `role`; with `userId`, as withUser does (app.user_id set
   * locally). The transaction commits unless `fn` throws.
   */
  as<T>(role: Role, fn: (tx: Queryable) => Promise<T>, userId?: string): Promise<T>
  /** Runs SQL as the migration superuser. */
  sql(query: string, params?: unknown[]): Promise<Record<string, unknown>[]>
  close(): Promise<void>
}

export async function createTestDatabase(): Promise<TestDatabase> {
  const pg = new PGlite()
  for (const file of [
    ...migrationFiles('core'),
    ...migrationFiles('audit-log'),
    ...migrationFiles('switches'),
    ...migrationFiles('router-gateway'),
  ]) {
    const text = readFileSync(file, 'utf8')
      .split('\n')
      .filter((line) => !/^create extension /i.test(line))
      .join('\n')
      .replaceAll('--> statement-breakpoint', '')
    await pg.exec(text)
  }
  const db = drizzle(pg)
  return {
    pg,
    async as(role, fn, userId) {
      return db.transaction(async (tx) => {
        if (role !== 'postgres') await tx.execute(`set local role ${role}`)
        if (userId) await tx.execute(`select set_config('app.user_id', '${userId}', true)`)
        return fn(tx as unknown as Queryable)
      })
    },
    async sql(query, params = []) {
      return (await pg.query<Record<string, unknown>>(query, params)).rows
    },
    close: () => pg.close(),
  }
}

/** Sets a switch, as the migration superuser (mirrors an admin change). */
export async function setSwitch(
  db: TestDatabase,
  state: 'off' | 'shadow' | 'on',
  name = 'router-gateway',
  kind: 'module' | 'provider' = 'module',
): Promise<void> {
  await db.sql(
    `insert into switches.switches (name, kind, state) values ($1, $2, $3)
     on conflict (name) do update set state = excluded.state`,
    [name, kind, state],
  )
}

/** Module on and the openrouteservice provider switch on: the gateway is open. */
export async function openGateway(db: TestDatabase): Promise<void> {
  await setSwitch(db, 'on')
  await setSwitch(db, 'on', 'openrouteservice', 'provider')
}
