// generated by scripts/new-module.mjs; edit freely
// Drizzle Kit configuration for the spec-match module's migrations. Paths are relative to
// packages/db, where `pnpm db:generate spec-match` runs. See packages/db/README.md.
import { defineConfig } from 'drizzle-kit'

export default defineConfig({
  dialect: 'postgresql',
  schema: './src/schema/spec-match.ts',
  out: './migrations/spec-match',
  schemaFilter: ['spec_match'],
  migrations: { prefix: 'supabase' },
})
