// generated by scripts/new-module.mjs; edit freely
// Drizzle Kit configuration for the search-planner module's migrations. Paths are relative to
// packages/db, where `pnpm db:generate search-planner` runs. See packages/db/README.md.
import { defineConfig } from 'drizzle-kit'

export default defineConfig({
  dialect: 'postgresql',
  schema: './src/schema/search-planner.ts',
  out: './migrations/search-planner',
  schemaFilter: ['search_planner'],
  migrations: { prefix: 'supabase' },
})
