// generated by scripts/new-module.mjs; edit freely
// Drizzle Kit configuration for the noise-filter module's migrations. Paths are relative to
// packages/db, where `pnpm db:generate noise-filter` runs. See packages/db/README.md.
import { defineConfig } from 'drizzle-kit'

export default defineConfig({
  dialect: 'postgresql',
  schema: './src/schema/noise-filter.ts',
  out: './migrations/noise-filter',
  schemaFilter: ['noise_filter'],
  migrations: { prefix: 'supabase' },
})
