// generated by scripts/new-module.mjs; edit freely
// Database access. Own tables from '@nabvy/db/schema/listing-card'; other modules' data only through
// their v_ views (packages/db/README.md). User rows only inside withUser.
import { ListingCard } from '@nabvy/contracts/modules/listing-card'
import { vListingCard } from '@nabvy/db/schema/listing-card'
import { inArray } from 'drizzle-orm'

type Queryable = import('@nabvy/db').Queryable

const iso = (value: Date | string | null): string | null =>
  value === null ? null : new Date(value).toISOString()

/**
 * The visible cards for these listing IDs, in `app.v_listing_card`'s own row shape (module card,
 * "Outputs: its view"). A listing that is off-switch, suppressed or missing is simply absent from
 * the result, never an error: the caller (an oRPC procedure) shows nothing for it.
 */
export async function cardsFor(
  q: Queryable,
  listingIds: readonly string[],
): Promise<ListingCard[]> {
  if (listingIds.length === 0) return []
  const rows = await q
    .select()
    .from(vListingCard)
    .where(inArray(vListingCard.listingId, listingIds))
  return rows.map((row) => ListingCard.parse({ ...row, listedAt: iso(row.listedAt) }))
}
