// generated by scripts/new-module.mjs; edit freely
// Drizzle Kit configuration for the listing-assessment module's migrations. Paths are relative to
// packages/db, where `pnpm db:generate listing-assessment` runs. See packages/db/README.md.
import { defineConfig } from 'drizzle-kit'

export default defineConfig({
  dialect: 'postgresql',
  schema: './src/schema/listing-assessment.ts',
  out: './migrations/listing-assessment',
  schemaFilter: ['listing_assessment'],
  migrations: { prefix: 'supabase' },
})
