// generated by scripts/new-module.mjs; edit freely
import { events, module } from '@nabvy/contracts/modules/suspected-labels'
import { describe, expect, it } from 'vitest'

describe('suspected-labels contracts', () => {
  it('declares its name', () => {
    expect(module).toBe('suspected-labels')
    expect(events.module).toBe('suspected-labels')
  })

  it.todo('every exported schema parses its documented shape and refuses the obvious bad input')
  it.todo('every event payload carries identifiers and times only, never text or prices (rule 7)')
})
