// generated by scripts/new-module.mjs; edit freely

import { evaluations } from '@nabvy/db/schema/suspected-labels'
import { and, eq } from 'drizzle-orm'
import { afterAll, beforeAll, describe, expect, it } from 'vitest'
import { createTestDatabase, type TestDatabase } from './support/database'

// Rule 8 of docs/design/modules/_rules.md: every handler and exported write function is
// idempotent on its key (source + sourceListingId + contentHash for card and detail stages, or
// the natural id + version for a run, job, cluster or group). Run each one twice on the same batch
// and assert the second run changes nothing.

let db: TestDatabase
beforeAll(async () => {
  db = await createTestDatabase()
}, 60_000)
afterAll(() => db.close())

describe('suspected-labels idempotency', () => {
  it('upsertEvaluation run twice with the same key writes once', async () => {
    const { upsertEvaluation } = await import('../src/repo/index')

    const evaluation = {
      source: 'test',
      source_listing_id: 'list-123',
      evidence_hash: 'hash-abc',
      rule_version: 'r1.0',
      signals: { test: true },
      paths_met: ['A'],
    }

    // First run
    await db.as('nabvy_pipeline', async (tx) => {
      await upsertEvaluation(tx, evaluation)
    })

    // Verify it was inserted
    const result1 = await db.as('nabvy_pipeline', async (tx) => {
      return tx
        .select()
        .from(evaluations)
        .where(
          and(
            eq(evaluations.source, evaluation.source),
            eq(evaluations.source_listing_id, evaluation.source_listing_id),
            eq(evaluations.evidence_hash, evaluation.evidence_hash),
            eq(evaluations.rule_version, evaluation.rule_version),
          ),
        )
    })

    expect(result1).toHaveLength(1)

    // Second run with same key
    await db.as('nabvy_pipeline', async (tx) => {
      await upsertEvaluation(tx, evaluation)
    })

    // Verify only one row exists (no duplicate)
    const result2 = await db.as('nabvy_pipeline', async (tx) => {
      return tx
        .select()
        .from(evaluations)
        .where(
          and(
            eq(evaluations.source, evaluation.source),
            eq(evaluations.source_listing_id, evaluation.source_listing_id),
            eq(evaluations.evidence_hash, evaluation.evidence_hash),
            eq(evaluations.rule_version, evaluation.rule_version),
          ),
        )
    })

    expect(result2).toHaveLength(1)
  })
})
