// generated by scripts/new-module.mjs; edit freely
// Drizzle Kit configuration for the inventory module's migrations. Paths are relative to
// packages/db, where `pnpm db:generate inventory` runs. See packages/db/README.md.
import { defineConfig } from 'drizzle-kit'

export default defineConfig({
  dialect: 'postgresql',
  schema: './src/schema/inventory.ts',
  out: './migrations/inventory',
  schemaFilter: ['inventory'],
  migrations: { prefix: 'supabase' },
})
