// generated by scripts/new-module.mjs; edit freely
// Drizzle Kit configuration for the warning-signs module's migrations. Paths are relative to
// packages/db, where `pnpm db:generate warning-signs` runs. See packages/db/README.md.
import { defineConfig } from 'drizzle-kit'

export default defineConfig({
  dialect: 'postgresql',
  schema: './src/schema/warning-signs.ts',
  out: './migrations/warning-signs',
  schemaFilter: ['warning_signs'],
  migrations: { prefix: 'supabase' },
})
