// generated by scripts/new-module.mjs; edit freely
// Drizzle Kit configuration for the seller-reply-reports module's migrations. Paths are relative to
// packages/db, where `pnpm db:generate seller-reply-reports` runs. See packages/db/README.md.
import { defineConfig } from 'drizzle-kit'

export default defineConfig({
  dialect: 'postgresql',
  schema: './src/schema/seller-reply-reports.ts',
  out: './migrations/seller-reply-reports',
  schemaFilter: ['seller_reply_reports'],
  migrations: { prefix: 'supabase' },
})
