// generated by scripts/new-module.mjs; edit freely
import { events, module } from '@nabvy/contracts/modules/asking-price-index'
import { describe, expect, it } from 'vitest'

describe('asking-price-index contracts', () => {
  it('declares its name', () => {
    expect(module).toBe('asking-price-index')
    expect(events.module).toBe('asking-price-index')
  })

  it.todo('every exported schema parses its documented shape and refuses the obvious bad input')
  it.todo('every event payload carries identifiers and times only, never text or prices (rule 7)')
})
