// generated by scripts/new-module.mjs; edit freely
import { afterAll, beforeAll, describe, it } from 'vitest'
import { createTestDatabase, type TestDatabase } from './support/database'

// Rule 8 of docs/design/modules/_rules.md: every handler and exported write function is
// idempotent on its key (source + sourceListingId + contentHash for card and detail stages, or
// the natural id + version for a run, job, cluster or group). Run each one twice on the same batch
// and assert the second run changes nothing.

let db: TestDatabase
beforeAll(async () => {
  db = await createTestDatabase()
}, 60_000)
afterAll(() => db.close())

describe('asking-price-index idempotency', () => {
  it.todo('a handler or write function run twice with the same key writes once')
})
