// generated by scripts/new-module.mjs; edit freely
import { state } from '@nabvy/switches'
import { afterAll, beforeAll, describe, expect, it } from 'vitest'
import { createTestDatabase, setSwitch, type TestDatabase } from './support/database'

// Rule 11 of docs/design/modules/_rules.md: one switch per module, off by default. Extend this
// file once asking-price-index has handlers or views to check against each state: off acknowledges events and
// writes nothing (its views return no rows); shadow runs and writes, but no user-facing view shows
// a row; on does the full job.

let db: TestDatabase
beforeAll(async () => {
  db = await createTestDatabase()
}, 60_000)
afterAll(() => db.close())

describe('asking-price-index switch', () => {
  it('reads off with no seed row', async () => {
    expect(await db.as('nabvy_pipeline', (tx) => state(tx, 'asking-price-index'))).toBe('off')
  })

  it('reads shadow and on once set', async () => {
    await setSwitch(db, 'shadow')
    expect(await db.as('nabvy_pipeline', (tx) => state(tx, 'asking-price-index'))).toBe('shadow')
    await setSwitch(db, 'on')
    expect(await db.as('nabvy_pipeline', (tx) => state(tx, 'asking-price-index'))).toBe('on')
  })

  it.todo('off: handlers acknowledge events and write nothing; views return no rows')
  it.todo('shadow: handlers write, but no user-facing view shows a row')
})
