// generated by scripts/new-module.mjs; edit freely
// Drizzle Kit configuration for the pickup-routes module's migrations. Paths are relative to
// packages/db, where `pnpm db:generate pickup-routes` runs. See packages/db/README.md.
import { defineConfig } from 'drizzle-kit'

export default defineConfig({
  dialect: 'postgresql',
  schema: './src/schema/pickup-routes.ts',
  out: './migrations/pickup-routes',
  schemaFilter: ['pickup_routes'],
  migrations: { prefix: 'supabase' },
})
