// node --test scripts/new-module.test.mjs
// Self-test of scripts/new-module.mjs, standalone (no vitest, no workspace deps beyond node:*).
// packages/db/test/scaffold.test.ts covers the same scaffold more thoroughly against the real
// tree's Drizzle Kit plan(); this file is the quick, dependency-free check that lives next to the
// script it tests.
import assert from 'node:assert/strict'
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join } from 'node:path'
import { after, describe, it } from 'node:test'
import { fileURLToPath } from 'node:url'
import { parseArgs, RESERVED_SCHEMAS, scaffoldModule, validateName } from './new-module.mjs'

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..')

const roots = []
after(() => {
  for (const root of roots.splice(0)) rmSync(root, { recursive: true, force: true })
})

function tempRoot() {
  const root = mkdtempSync(join(tmpdir(), 'nabvy-new-module-'))
  roots.push(root)
  mkdirSync(join(root, 'services', 'usage-ledger'), { recursive: true })
  writeFileSync(
    join(root, 'services', 'usage-ledger', 'package.json'),
    readFileSync(join(repoRoot, 'services', 'usage-ledger', 'package.json')),
  )
  return root
}

describe('validateName', () => {
  it('accepts kebab case and maps it to a snake_case schema', () => {
    assert.equal(validateName('copy-advert-spam'), 'copy_advert_spam')
  })

  it('refuses bad, empty and reserved names', () => {
    for (const name of [undefined, '', 'Bad_Name', 'auth', 'db', 'core', 'nabvy-core', 'pg-stat']) {
      assert.throws(() => validateName(name))
    }
  })

  it('reserves every schema the scaffold refuses', () => {
    for (const schema of RESERVED_SCHEMAS) {
      assert.throws(() => validateName(schema.replaceAll('_', '-')), `${schema} should be reserved`)
    }
  })
})

describe('parseArgs', () => {
  it('reads the module name with no flags', () => {
    assert.deepEqual(parseArgs(['throwaway-probe']), {
      name: 'throwaway-probe',
      dependsOn: undefined,
    })
  })

  it('splits --depends-on into a trimmed, non-empty list', () => {
    assert.deepEqual(parseArgs(['throwaway-probe', '--depends-on=core, switches']), {
      name: 'throwaway-probe',
      dependsOn: ['core', 'switches'],
    })
  })

  it('ignores an unrelated flag', () => {
    assert.deepEqual(parseArgs(['throwaway-probe', '--verbose']), {
      name: 'throwaway-probe',
      dependsOn: undefined,
    })
  })
})

describe('scaffoldModule', () => {
  it('writes the merged shape and refuses to run twice', () => {
    const root = tempRoot()
    const written = scaffoldModule({ root, name: 'throwaway-probe' })
    assert.ok(written.length > 15, `expected a full file set, got ${written.length} files`)
    for (const path of written) assert.ok(existsSync(join(root, path)), path)

    assert.throws(() => scaffoldModule({ root, name: 'throwaway-probe' }), /already exists/)
  })

  it('defaults dependsOn to ["core"] and takes an explicit list', () => {
    const a = tempRoot()
    scaffoldModule({ root: a, name: 'throwaway-probe' })
    const defaultManifest = JSON.parse(
      readFileSync(join(a, 'packages/db/migrations/throwaway-probe/module.json'), 'utf8'),
    )
    assert.deepEqual(defaultManifest.dependsOn, ['core'])

    const b = tempRoot()
    scaffoldModule({ root: b, name: 'throwaway-probe', dependsOn: ['core', 'switches'] })
    const explicitManifest = JSON.parse(
      readFileSync(join(b, 'packages/db/migrations/throwaway-probe/module.json'), 'utf8'),
    )
    assert.deepEqual(explicitManifest.dependsOn, ['core', 'switches'])
  })

  it('carries the generated-by comment on every file that can hold one', () => {
    const root = tempRoot()
    const written = scaffoldModule({ root, name: 'throwaway-probe' })
    const marker = 'generated by scripts/new-module.mjs; edit freely'
    for (const path of written) {
      if (path.endsWith('.json')) continue
      assert.ok(readFileSync(join(root, path), 'utf8').includes(marker), path)
    }
  })

  it('copies the exact workspace dependencies services/usage-ledger/package.json declares', () => {
    const root = tempRoot()
    scaffoldModule({ root, name: 'throwaway-probe' })
    const generated = JSON.parse(
      readFileSync(join(root, 'services/throwaway-probe/package.json'), 'utf8'),
    )
    const reference = JSON.parse(
      readFileSync(join(root, 'services/usage-ledger/package.json'), 'utf8'),
    )
    assert.deepEqual(generated.dependencies, reference.dependencies)
    assert.deepEqual(generated.devDependencies, reference.devDependencies)
  })
})
