// pnpm new:module <name> [--depends-on=core,switches]
// Scaffolds an atomic module (docs/decisions.md, "Atomic modules") in the merged shape
// services/usage-ledger uses, in exactly the files that module owns (docs/design/modules/_rules.md,
// rule 2), so parallel module branches never edit a shared file:
//   services/<name>/                          the module package (CLAUDE.md, _rules.md rule 2)
//   packages/contracts/src/modules/<name>.ts  its contracts and event registry
//   packages/config/src/modules/<name>.ts     its thresholds (_rules.md rule 14)
//   packages/db/src/schema/<name>.ts          its Drizzle tables, in its own Postgres schema
//   packages/db/migrations/<name>/            its migrations home: module.json + drizzle.config.ts
//   packages/db/tests/<name>.test.sql         its pnpm db:dry-run probe
// Then: pnpm install, define tables, pnpm db:generate <name> (packages/db/README.md).
//
// Every generated file it can carry a comment in opens with one line, "generated by
// scripts/new-module.mjs; edit freely", so a build session knows nothing here is sacred.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const MODULE_NAME = /^[a-z][a-z0-9]*(-[a-z0-9]+)*$/
// Keep in step with RESERVED_SCHEMAS in packages/db/src/module-schema.ts (a test checks this).
export const RESERVED_SCHEMAS = [
  'public',
  'auth',
  'storage',
  'realtime',
  'extensions',
  'graphql',
  'graphql_public',
  'vault',
  'net',
  'cron',
  'pgmq',
  'pgsodium',
  'supabase_functions',
  'supabase_migrations',
  'information_schema',
  'nabvy_core',
  'apify_gateway',
  'marketplace_monitor',
]
const RESERVED_NAMES = ['core', 'config', 'contracts', 'db', 'packs', 'web']

const GENERATED_BY = 'generated by scripts/new-module.mjs; edit freely'
const hashComment = (text) => `-- ${text}\n`
const slashComment = (text) => `// ${text}\n`
const mdComment = (text) => `<!-- ${text} -->\n`

const pascal = (name) =>
  name
    .split('-')
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join('')

export function validateName(name) {
  if (!name || !MODULE_NAME.test(name)) {
    throw new Error(`Module name "${name ?? ''}" must be kebab case, e.g. copy-advert-spam`)
  }
  const schema = name.replaceAll('-', '_')
  if (
    RESERVED_NAMES.includes(name) ||
    RESERVED_SCHEMAS.includes(schema) ||
    schema.startsWith('pg_')
  ) {
    throw new Error(`Module name "${name}" is reserved`)
  }
  return schema
}

/** Parses `<name> [--depends-on=a,b]` from argv (after the node and script path). */
export function parseArgs(argv) {
  const [name, ...rest] = argv
  let dependsOn
  for (const arg of rest) {
    const match = /^--depends-on=(.*)$/.exec(arg)
    if (match) {
      dependsOn = match[1]
        .split(',')
        .map((part) => part.trim())
        .filter(Boolean)
    }
  }
  return { name, dependsOn }
}

/**
 * The workspace dependencies a generated module's package.json carries: exactly what
 * services/usage-ledger/package.json uses (the reference shape task 0.13 was told to match), so
 * the two never drift apart by hand.
 */
function referenceDependencies(root) {
  const pkg = JSON.parse(readFileSync(join(root, 'services/usage-ledger/package.json'), 'utf8'))
  if (!pkg.dependencies?.zod)
    throw new Error('services/usage-ledger/package.json has no zod dependency')
  return { dependencies: pkg.dependencies, devDependencies: pkg.devDependencies ?? {} }
}

function files(name, schema, dependsOn, deps) {
  const Name = pascal(name)
  const migrationsRelative = '../../../../packages/db/migrations/'

  return {
    [`services/${name}/package.json`]: `${JSON.stringify(
      {
        name: `@nabvy/${name}`,
        version: '0.0.0',
        private: true,
        type: 'module',
        exports: { '.': './src/index.ts' },
        scripts: { typecheck: 'tsc --noEmit', test: 'vitest run' },
        dependencies: deps.dependencies,
        devDependencies: deps.devDependencies,
      },
      null,
      2,
    )}\n`,

    [`services/${name}/tsconfig.json`]: `{
  "extends": "../../tsconfig.base.json",
  "compilerOptions": {
    "types": ["node"]
  },
  "include": ["src", "test"]
}
`,

    [`services/${name}/vitest.config.ts`]: `${slashComment(GENERATED_BY)}import { defineConfig } from 'vitest/config'

export default defineConfig({
  test: {
    include: ['test/**/*.test.ts'],
    hookTimeout: 60000,
    testTimeout: 30000,
  },
})
`,

    [`services/${name}/README.md`]: `${mdComment(GENERATED_BY)}
# @nabvy/${name}

TODO: one sentence, the job (\`docs/design/modules/_rules.md\`, rule 15). A module session edits
only this folder, \`packages/contracts/src/modules/${name}.ts\`,
\`packages/config/src/modules/${name}.ts\`, \`packages/db/src/schema/${name}.ts\`,
\`packages/db/tests/${name}.test.sql\` and \`packages/db/migrations/${name}/\`.

## Switch and priority

Off by default (rule 11 of \`_rules.md\`; no seed row, so \`switches.state('${name}')\` reads
\`off\`). TODO: what users lose while it is off, and the priority with its source.

## Inputs

TODO: events consumed (each with its producing module); views and functions read (each with its
module).

## Outputs

TODO: events emitted (each with its idempotency key and the T-timestamp it stamps, rule 7);
internal, restricted and user-facing views (user-facing ones with their column list, rule 5);
exported functions.

## Tables

Postgres schema \`${schema}\`. TODO: each table, its key columns and its unique keys.

## Rules and thresholds

| Rule | Value | Basis | Status |
| --- | --- | --- | --- |
| TODO | TODO | TODO | starting value |

## Fixtures and pass rate

TODO: the cases, the recorded runs used (if any), synthetic cases and what they are built from,
the latest pass rate. A stage registers itself by file name, no shared file to edit:
\`test/fixtures/<stage>.fixtures.ts\` (\`fixtures/README.md\`, "How a module registers a stage").

## Decisions

TODO: dated notes on anything decided while building this module (\`CLAUDE.md\`, "Definition of
done").

## Open questions

\`docs/questions/${name}.md\` (never \`docs/questions.md\` itself: \`docs/session-conventions.md\`).

## Incidents

None.
`,

    [`services/${name}/src/index.ts`]: `${slashComment(GENERATED_BY)}// Public API of the ${name} module: the functions other modules and tasks may call.
// Other modules import from '@nabvy/${name}' only, never from its internals.
export { events, module } from '@nabvy/contracts/modules/${name}'
`,

    [`services/${name}/src/handlers/index.ts`]: `${slashComment(GENERATED_BY)}// Event handlers. Each takes a batch (100-500 items), is idempotent (key
// source + sourceListingId + contentHash, or the natural id + version) and stamps its
// T-timestamps (CLAUDE.md; _rules.md rules 8-10).
export {}
`,

    [`services/${name}/src/domain/index.ts`]: `${slashComment(GENERATED_BY)}// Pure logic: no I/O, no database, no clock or randomness passed in implicitly.
export {}
`,

    [`services/${name}/src/repo/index.ts`]: `${slashComment(GENERATED_BY)}// Database access. Own tables from '@nabvy/db/schema/${name}'; other modules' data only through
// their v_ views (packages/db/README.md). User rows only inside withUser.
export {}
`,

    [`services/${name}/test/support/database.ts`]: `${slashComment(GENERATED_BY)}import { readdirSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { PGlite } from '@electric-sql/pglite'
import type { Queryable } from '@nabvy/db'
import { drizzle } from 'drizzle-orm/pglite'

// An in-process Postgres (PGlite) with the core, audit-log, switches and ${name} migrations
// applied (packages/db/README.md), so the tests exercise the actual tables, grants, policies and
// triggers. Add another module's migrations here (for example better-auth, for an account check)
// once this module reads its tables or functions. PGlite has no PostGIS, pgvector or pg_trgm; skip
// them here unless this module needs one. The full migration set runs on real Postgres in
// \`pnpm db:dry-run\` (packages/db/tests/${name}.test.sql).

const migrations = fileURLToPath(new URL('${migrationsRelative}', import.meta.url))

function migrationFiles(module: string): string[] {
  const dir = join(migrations, module)
  return readdirSync(dir)
    .filter((name) => /^\\d{14}_.+\\.sql$/.test(name))
    .sort()
    .map((name) => join(dir, name))
}

export type Role = 'postgres' | 'nabvy_app' | 'nabvy_pipeline'

export interface TestDatabase {
  pg: PGlite
  /**
   * Runs \`fn\` in one transaction as \`role\`; with \`userId\`, as withUser does (app.user_id set
   * locally). The transaction commits unless \`fn\` throws.
   */
  as<T>(role: Role, fn: (tx: Queryable) => Promise<T>, userId?: string): Promise<T>
  /** Runs SQL as the migration superuser. */
  sql(query: string, params?: unknown[]): Promise<Record<string, unknown>[]>
  close(): Promise<void>
}

export async function createTestDatabase(): Promise<TestDatabase> {
  const pg = new PGlite()
  for (const file of [
    ...migrationFiles('core'),
    ...migrationFiles('audit-log'),
    ...migrationFiles('switches'),
    ...migrationFiles('${name}'),
  ]) {
    const text = readFileSync(file, 'utf8')
      .split('\\n')
      .filter((line) => !/^create extension /i.test(line))
      .join('\\n')
      .replaceAll('--> statement-breakpoint', '')
    await pg.exec(text)
  }
  const db = drizzle(pg)
  return {
    pg,
    async as(role, fn, userId) {
      return db.transaction(async (tx) => {
        if (role !== 'postgres') await tx.execute(\`set local role \${role}\`)
        if (userId) await tx.execute(\`select set_config('app.user_id', '\${userId}', true)\`)
        return fn(tx as unknown as Queryable)
      })
    },
    async sql(query, params = []) {
      return (await pg.query<Record<string, unknown>>(query, params)).rows
    },
    close: () => pg.close(),
  }
}

/** Sets this module's switch, as the migration superuser (mirrors an admin change). */
export async function setSwitch(db: TestDatabase, state: 'off' | 'shadow' | 'on'): Promise<void> {
  await db.sql(
    \`insert into switches.switches (name, kind, state) values ('${name}', 'module', $1)
     on conflict (name) do update set state = excluded.state\`,
    [state],
  )
}
`,

    [`services/${name}/test/switch.test.ts`]: `${slashComment(GENERATED_BY)}import { state } from '@nabvy/switches'
import { afterAll, beforeAll, describe, expect, it } from 'vitest'
import { createTestDatabase, setSwitch, type TestDatabase } from './support/database'

// Rule 11 of docs/design/modules/_rules.md: one switch per module, off by default. Extend this
// file once ${name} has handlers or views to check against each state: off acknowledges events and
// writes nothing (its views return no rows); shadow runs and writes, but no user-facing view shows
// a row; on does the full job.

let db: TestDatabase
beforeAll(async () => {
  db = await createTestDatabase()
}, 60_000)
afterAll(() => db.close())

describe('${name} switch', () => {
  it('reads off with no seed row', async () => {
    expect(await db.as('nabvy_pipeline', (tx) => state(tx, '${name}'))).toBe('off')
  })

  it('reads shadow and on once set', async () => {
    await setSwitch(db, 'shadow')
    expect(await db.as('nabvy_pipeline', (tx) => state(tx, '${name}'))).toBe('shadow')
    await setSwitch(db, 'on')
    expect(await db.as('nabvy_pipeline', (tx) => state(tx, '${name}'))).toBe('on')
  })

  it.todo('off: handlers acknowledge events and write nothing; views return no rows')
  it.todo('shadow: handlers write, but no user-facing view shows a row')
})
`,

    [`services/${name}/test/idempotency.test.ts`]: `${slashComment(GENERATED_BY)}import { afterAll, beforeAll, describe, it } from 'vitest'
import { createTestDatabase, type TestDatabase } from './support/database'

// Rule 8 of docs/design/modules/_rules.md: every handler and exported write function is
// idempotent on its key (source + sourceListingId + contentHash for card and detail stages, or
// the natural id + version for a run, job, cluster or group). Run each one twice on the same batch
// and assert the second run changes nothing.

let db: TestDatabase
beforeAll(async () => {
  db = await createTestDatabase()
}, 60_000)
afterAll(() => db.close())

describe('${name} idempotency', () => {
  it.todo('a handler or write function run twice with the same key writes once')
})
`,

    [`services/${name}/test/contracts.test.ts`]: `${slashComment(GENERATED_BY)}import { events, module } from '@nabvy/contracts/modules/${name}'
import { describe, expect, it } from 'vitest'

describe('${name} contracts', () => {
  it('declares its name', () => {
    expect(module).toBe('${name}')
    expect(events.module).toBe('${name}')
  })

  it.todo('every exported schema parses its documented shape and refuses the obvious bad input')
  it.todo('every event payload carries identifiers and times only, never text or prices (rule 7)')
})
`,

    [`packages/contracts/src/modules/${name}.ts`]: `${slashComment(GENERATED_BY)}import { defineEvents } from '../index'

// Contracts of the ${name} module (packages/contracts/README.md): its schemas and its events.
// Import from '@nabvy/contracts/modules/${name}'. Samples in fixtures/contracts/${name}/.
// Schemas use Zod with the shared primitives, for example:
//   import { z } from 'zod'
//   import { IsoTimestamp, Uuid } from '../index'
//   export const ${Name}Seen = z.strictObject({ thingId: Uuid, seenAt: IsoTimestamp })
//   export type ${Name}Seen = z.infer<typeof ${Name}Seen>

export const module = '${name}'

/** Events this module publishes. A breaking payload change adds a version (README.md). */
export const events = defineEvents(module, {
  // 'thing.seen': { 1: z.object({ thingIds: z.array(Uuid).min(1).max(500) }) },
})
`,

    [`packages/config/src/modules/${name}.ts`]: `${slashComment(GENERATED_BY)}import { z } from 'zod'

// Thresholds of the ${name} module (rule 14 of docs/design/modules/_rules.md). Each value carries
// a comment with its basis (a cited measurement or rule) and is a starting value until this
// module's fixtures calibrate it. No prices here: those cross a boundary and belong in contracts
// or in a pricing module.

const ${schema}Config = z.object({})

/** No thresholds yet. Add one here, parsed and exported, once this module needs a starting value. */
export const config = ${schema}Config.parse({})
`,

    [`packages/db/src/schema/${name}.ts`]: `${slashComment(GENERATED_BY)}import { moduleSchema } from '../module-schema'

// Tables of the ${name} module, all in the Postgres schema '${schema}' (packages/db/README.md).
// Only services/${name} writes them. Other modules import only the views (v-prefixed exports).
// After changing this file: pnpm db:generate ${name}

export const schema = moduleSchema('${name}')
`,

    // Biome formats a short array of strings on one line; JSON.stringify's indenter never does,
    // so this is built by hand to match what pnpm lint (and every committed module.json) expects.
    [`packages/db/migrations/${name}/module.json`]: `{
  "module": ${JSON.stringify(name)},
  "schema": ${JSON.stringify(schema)},
  "dependsOn": [${dependsOn.map((d) => JSON.stringify(d)).join(', ')}]
}
`,

    [`packages/db/migrations/${name}/drizzle.config.ts`]: `${slashComment(GENERATED_BY)}// Drizzle Kit configuration for the ${name} module's migrations. Paths are relative to
// packages/db, where \`pnpm db:generate ${name}\` runs. See packages/db/README.md.
import { defineConfig } from 'drizzle-kit'

export default defineConfig({
  dialect: 'postgresql',
  schema: './src/schema/${name}.ts',
  out: './migrations/${name}',
  schemaFilter: ['${schema}'],
  migrations: { prefix: 'supabase' },
})
`,

    [`packages/db/tests/${name}.test.sql`]: `${hashComment(GENERATED_BY)}-- ${name} (services/${name}): TODO describe what this file proves. Rolled back.
begin;
set local client_min_messages = warning;

-- No Data API role reaches the schema, and this module's views (once it has any) follow the view
-- conventions (packages/db/README.md, "Views").
do $$
begin
  if has_schema_privilege('anon', '${schema}', 'usage')
     or has_schema_privilege('authenticated', '${schema}', 'usage') then
    raise exception '${schema} is reachable by a Data API role';
  end if;
  if exists (select 1 from nabvy_core.view_violations() where view_name like '${schema}.%') then
    raise exception '${schema} views break the view conventions';
  end if;
end;
$$;

-- TODO once this module has tables: seed rows as the owning role, RLS isolation between users
-- (set_config('app.user_id', ..., true)), and the switch-filtered view behaviour
-- (packages/db/README.md, "Adding tables to a module").

rollback;
`,
  }
}

/** Writes the module's files under `root`. Refuses to overwrite anything. Returns the paths. */
export function scaffoldModule({ root, name, dependsOn = ['core'] }) {
  const schema = validateName(name)
  const deps = referenceDependencies(root)
  const planned = files(name, schema, dependsOn, deps)
  const clashes = [
    `services/${name}`,
    `packages/db/migrations/${name}`,
    ...Object.keys(planned),
  ].filter((path) => existsSync(join(root, path)))
  if (clashes.length > 0) throw new Error(`Module "${name}" already exists: ${clashes.join(', ')}`)
  for (const [path, content] of Object.entries(planned)) {
    mkdirSync(dirname(join(root, path)), { recursive: true })
    writeFileSync(join(root, path), content)
  }
  for (const dir of ['src/handlers', 'src/domain', 'src/repo', 'test/support']) {
    mkdirSync(join(root, 'services', name, dir), { recursive: true })
  }
  return Object.keys(planned)
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const root = join(dirname(fileURLToPath(import.meta.url)), '..')
  try {
    const { name, dependsOn } = parseArgs(process.argv.slice(2))
    const written = scaffoldModule({ root, name, ...(dependsOn ? { dependsOn } : {}) })
    for (const path of written) console.log(`create ${path}`)
    console.log(`\nNext: pnpm install, then see packages/db/README.md to add tables.`)
  } catch (error) {
    console.error(error.message)
    process.exit(1)
  }
}
