-- generated by scripts/new-module.mjs; edit freely
-- asking-price-index (services/asking-price-index): TODO describe what this file proves. Rolled back.
begin;
set local client_min_messages = warning;

-- No Data API role reaches the schema, and this module's views (once it has any) follow the view
-- conventions (packages/db/README.md, "Views").
do $$
begin
  if has_schema_privilege('anon', 'asking_price_index', 'usage')
     or has_schema_privilege('authenticated', 'asking_price_index', 'usage') then
    raise exception 'asking_price_index is reachable by a Data API role';
  end if;
  if exists (select 1 from nabvy_core.view_violations() where view_name like 'asking_price_index.%') then
    raise exception 'asking_price_index views break the view conventions';
  end if;
end;
$$;

-- TODO once this module has tables: seed rows as the owning role, RLS isolation between users
-- (set_config('app.user_id', ..., true)), and the switch-filtered view behaviour
-- (packages/db/README.md, "Adding tables to a module").

rollback;
