// generated by scripts/new-module.mjs; edit freely
import { z } from 'zod'

// Thresholds of the copy-advert module (rule 14 of docs/design/modules/_rules.md). Each value carries
// a comment with its basis (a cited measurement or rule) and is a starting value until this
// module's fixtures calibrate it. No prices here: those cross a boundary and belong in contracts
// or in a pricing module.

const copy_advertConfig = z.object({})

/** No thresholds yet. Add one here, parsed and exported, once this module needs a starting value. */
export const config = copy_advertConfig.parse({})
