// generated by scripts/new-module.mjs; edit freely
import { defineConfig } from 'vitest/config'

export default defineConfig({
  test: {
    include: ['test/**/*.test.ts'],
    hookTimeout: 60000,
    testTimeout: 30000,
  },
})
