import { z } from 'zod'
import { AmountMinor, Currency, defineEvents, IsoTimestamp, Money, Source, Uuid } from '../index'
import { ProductCatalogueId } from './product-catalogue'

// Contracts of the inventory module (services/inventory, docs/design/modules/inventory.md): the
// items a user bought and sold, entered by the user, and the `inventory.outcome-recorded` event.
// Import from '@nabvy/contracts/modules/inventory'. Every amount here is what the user typed
// (CLAUDE.md, "No invented numbers"): the module never estimates a cost or a sale price. The
// product key is product-catalogue's, and money is the shared `Money`, narrowed, never retyped.

export const module = 'inventory'

/**
 * The most an item may cost or sell for: £1,000,000.00 (or €), in minor units. A bound on user
 * input, not a price; nothing the app ever computes.
 */
export const INVENTORY_MAX_AMOUNT_MINOR = 100_000_000

/** No item was bought before this date; a bound on user input, so a typo never makes a 1970 row. */
export const INVENTORY_EARLIEST_DATE = '2000-01-01'

/** A user-entered amount: whole minor units, never negative, never past the bound above. */
export const InventoryAmountMinor = AmountMinor.min(0).max(INVENTORY_MAX_AMOUNT_MINOR)
export type InventoryAmountMinor = z.infer<typeof InventoryAmountMinor>

/** The shared `Money`, with the amount bounded for user input. GBP and EUR stay apart. */
export const InventoryMoney = Money.extend({ amountMinor: InventoryAmountMinor })
export type InventoryMoney = z.infer<typeof InventoryMoney>

/** A calendar date the user picked (`YYYY-MM-DD`), no earlier than INVENTORY_EARLIEST_DATE. */
export const InventoryDate = z.iso.date().refine((value) => value >= INVENTORY_EARLIEST_DATE, {
  message: `a date must not be before ${INVENTORY_EARLIEST_DATE}`,
})
export type InventoryDate = z.infer<typeof InventoryDate>

/**
 * The "I bought this" form. `itemId` is generated by the client, so a resubmitted form is the
 * same item and never a second row. At least one of `productKey`, `sourceListingId` (a row of
 * `app.v_listing_card`) and `scanId` (one of the user's own scans) names what was bought. The
 * upper bound on `boughtAt` (never in the future) is checked against server time by the module,
 * not here (PR template: caps and windows never come from caller input).
 */
export const InventoryAddItemInput = z
  .strictObject({
    itemId: Uuid,
    userId: Uuid,
    productKey: ProductCatalogueId.nullable().optional(),
    sourceListingId: Uuid.nullable().optional(),
    scanId: Uuid.nullable().optional(),
    cost: InventoryMoney,
    boughtAt: InventoryDate,
  })
  .refine((input) => !!(input.productKey || input.sourceListingId || input.scanId), {
    message: 'an item needs a product key, a source listing or a scan',
  })
export type InventoryAddItemInput = z.input<typeof InventoryAddItemInput>

/**
 * The "I sold this" form. `sold` must be in the item's own currency (the module refuses a
 * mismatch: amounts are never converted). `soldOn` is the marketplace it sold on, one of the
 * shared `Source` values, or absent when the user does not say.
 */
export const InventoryRecordSaleInput = z.strictObject({
  userId: Uuid,
  itemId: Uuid,
  sold: InventoryMoney,
  soldAt: InventoryDate,
  soldOn: Source.nullable().optional(),
})
export type InventoryRecordSaleInput = z.input<typeof InventoryRecordSaleInput>

/**
 * One row of the user-facing view `app.v_inventory_items`: the caller's own items. `profitMinor`
 * is `soldMinor - costMinor`, arithmetic over the user's own two numbers, null until sold. No
 * seller field, no listing content: only what the user entered and the IDs that name it.
 * `sourceListingId` reads null while that listing is suppressed or `listing-suppression` is off.
 */
export const InventoryItem = z.strictObject({
  id: Uuid,
  productKey: ProductCatalogueId.nullable(),
  sourceListingId: Uuid.nullable(),
  scanId: Uuid.nullable(),
  currency: Currency,
  costMinor: InventoryAmountMinor,
  boughtAt: z.iso.date(),
  soldMinor: InventoryAmountMinor.nullable(),
  soldAt: z.iso.date().nullable(),
  soldOn: Source.nullable(),
  profitMinor: AmountMinor.nullable(),
})
export type InventoryItem = z.infer<typeof InventoryItem>

/**
 * One row of the internal view `inventory.v_items` (read by `sold-reports`, which asks the user
 * for separate consent before any amount enters an aggregate). Carries the user ID, so it is
 * never granted to `nabvy_app`. `soldRecordedAt` is server time, the stamp a reader orders by.
 */
export const InventoryItemInternal = z.strictObject({
  id: Uuid,
  userId: Uuid,
  productKey: ProductCatalogueId.nullable(),
  currency: Currency,
  costMinor: InventoryAmountMinor,
  boughtAt: z.iso.date(),
  soldMinor: InventoryAmountMinor.nullable(),
  soldAt: z.iso.date().nullable(),
  soldOn: Source.nullable(),
  soldRecordedAt: IsoTimestamp.nullable(),
})
export type InventoryItemInternal = z.infer<typeof InventoryItemInternal>

/** Error codes returned as values (rule 3 of docs/design/modules/_rules.md). */
export const InventoryErrorCode = z.enum([
  'inventory.off', //                the module is off: inventory is unavailable
  'inventory.invalid_input', //      the form failed its schema
  'inventory.account_restricted', // the account is suspended or banned
  'inventory.not_found', //          no such item for this user
  'inventory.listing_not_found', //  the source listing is not on the user's listing card
  'inventory.scan_not_found', //     the scan is not one of the user's own
  'inventory.conflict', //           the item ID exists with different input, or is not this user's
  'inventory.currency_mismatch', //  the sale is in another currency than the cost
  'inventory.date_order', //         sold before bought, or a date after today
])
export type InventoryErrorCode = z.infer<typeof InventoryErrorCode>

export const InventoryError = z.strictObject({
  code: InventoryErrorCode,
  message: z.string().min(1),
})
export type InventoryError = z.infer<typeof InventoryError>

/** The payload of `inventory.outcome-recorded`: item IDs only (rule 7), 1-500 per envelope. */
export const InventoryOutcomeRecordedEvent = z.strictObject({
  itemIds: z.array(Uuid).min(1).max(500),
})
export type InventoryOutcomeRecordedEvent = z.infer<typeof InventoryOutcomeRecordedEvent>

/** Events this module publishes. A breaking payload change adds a version (README.md). */
export const events = defineEvents(module, {
  /** A sale was recorded on an item, or corrected. Never emitted for adding an item. */
  'inventory.outcome-recorded': { 1: InventoryOutcomeRecordedEvent },
})
