import { z } from 'zod'
import { defineEvents, IsoTimestamp, Uuid } from '../index'
import { ProductCatalogueId } from './product-catalogue'

// Contracts of the scan-recognition module (services/scan-recognition, docs/design/modules/
// scan-recognition.md): what a scan submits, what the vision model may return, what a scan
// resolves to, and the `scan-recognition.identified` event. Import from
// '@nabvy/contracts/modules/scan-recognition'. Samples in fixtures/contracts/scan-recognition/.
// No schema here carries a price: prices come only from `services/valuation` over real
// comparables (CLAUDE.md), so this module never reads or writes one.

export const module = 'scan-recognition'

/** Photo types and size accepted for a scan (docs/security.md, "Uploads"). */
export const ScanRecognitionPhotoMediaType = z.enum(['image/jpeg', 'image/png', 'image/webp'])
export type ScanRecognitionPhotoMediaType = z.infer<typeof ScanRecognitionPhotoMediaType>
export const SCAN_RECOGNITION_PHOTO_MAX_BYTES = 10 * 1024 * 1024

/**
 * A photo already uploaded to storage under the user's own path `scans/<userId>/<file>` (docs/
 * security.md: "stored under a per-user path"). The module never receives the bytes; the model
 * client loads them by `ref`.
 */
export const ScanRecognitionPhoto = z.strictObject({
  ref: z
    .string()
    .regex(/^scans\/[0-9a-f-]{36}\/[A-Za-z0-9._-]{1,100}$/)
    .max(200),
  mediaType: ScanRecognitionPhotoMediaType,
  bytes: z.int().positive().max(SCAN_RECOGNITION_PHOTO_MAX_BYTES),
})
export type ScanRecognitionPhoto = z.infer<typeof ScanRecognitionPhoto>

/** An EAN-8, UPC-A, EAN-13 or GTIN-14 read on the device (docs/scan-mode.md, "Capture"). */
export const ScanRecognitionBarcode = z.string().regex(/^(\d{8}|\d{12,14})$/)
export type ScanRecognitionBarcode = z.infer<typeof ScanRecognitionBarcode>

/**
 * The scan form. `scanId` is generated by the client, so a resubmitted form is the same scan and
 * never a second model call. At least one of `barcode` and `photo` is present, and the photo sits
 * under the scanning user's own path. No client time: the scan's `at` is stamped by the server,
 * because the spend-cap window and photo expiry are measured from it (review of PR #41).
 */
export const ScanRecognitionScanInput = z
  .strictObject({
    scanId: Uuid,
    userId: Uuid,
    barcode: ScanRecognitionBarcode.optional(),
    photo: ScanRecognitionPhoto.optional(),
  })
  .refine((input) => input.barcode !== undefined || input.photo !== undefined, {
    message: 'a scan needs a barcode or a photo',
  })
  .refine((input) => !input.photo || input.photo.ref.startsWith(`scans/${input.userId}/`), {
    message: "the photo must be under the user's own path",
    path: ['photo', 'ref'],
  })
export type ScanRecognitionScanInput = z.input<typeof ScanRecognitionScanInput>

const fact = z.string().trim().min(1).max(100).nullable()

/**
 * What the vision model returns (docs/contracts.md, "Recognition"): facts and text only. The
 * model names candidates in words; the module resolves each name through product-catalogue's
 * `resolve()`, so the model never chooses a catalogue ID (rule 13 of docs/design/modules/
 * _rules.md). There is no sticker price field: this module never writes a price (README.md,
 * "Decisions").
 */
export const ScanRecognitionOutput = z.strictObject({
  description: z.strictObject({
    type: fact,
    brand: fact,
    model: fact,
    colour: fact,
    material: fact,
    size: fact,
    condition: fact,
  }),
  candidates: z
    .array(
      z.strictObject({
        name: z.string().trim().min(1).max(200),
        confidence: z.number().min(0).max(1),
      }),
    )
    .max(3),
  searchPhrases: z.array(z.string().trim().min(1).max(100)).max(5),
})
export type ScanRecognitionOutput = z.infer<typeof ScanRecognitionOutput>

/** How a scan was identified. `cex_box` is reserved for the soft `cex-adapter` (README.md). */
export const ScanRecognitionMethod = z.enum(['barcode', 'cex_box', 'vision', 'none'])
export type ScanRecognitionMethod = z.infer<typeof ScanRecognitionMethod>

/**
 * Where a scan stands. `identified`: a barcode resolved, or the top candidate reached the
 * confirmation threshold, or the user confirmed one. `needs_confirmation`: below the threshold,
 * the app asks the user to confirm or pick (docs/scan-mode.md, "Identify"). `unidentified`: no
 * candidate resolved to a catalogue item, or the model's output failed validation.
 */
export const ScanRecognitionStatus = z.enum(['identified', 'needs_confirmation', 'unidentified'])
export type ScanRecognitionStatus = z.infer<typeof ScanRecognitionStatus>

/** What `scan()` returns to the scan procedure. */
export const ScanRecognitionResult = z.strictObject({
  scanId: Uuid,
  status: ScanRecognitionStatus,
  method: ScanRecognitionMethod,
  identified: ProductCatalogueId.nullable(),
  candidates: z.array(ProductCatalogueId).max(3),
  confidence: z.number().min(0).max(1).nullable(),
  searchPhrases: z.array(z.string()).max(5),
  modelCalled: z.boolean(),
})
export type ScanRecognitionResult = z.infer<typeof ScanRecognitionResult>

/** The user confirms or picks one of the scan's candidates (docs/scan-mode.md, "Identify"). */
export const ScanRecognitionConfirmInput = z.strictObject({
  scanId: Uuid,
  userId: Uuid,
  catalogueId: ProductCatalogueId,
})
export type ScanRecognitionConfirmInput = z.infer<typeof ScanRecognitionConfirmInput>

/** One row of the internal view `scan_recognition.v_scans` (packages/db/src/schema/scan-recognition.ts). */
export const ScanRecognitionScan = z.strictObject({
  id: Uuid,
  userId: Uuid,
  method: ScanRecognitionMethod,
  status: ScanRecognitionStatus,
  identified: ProductCatalogueId.nullable(),
  confidence: z.number().min(0).max(1).nullable(),
  confirmed: z.boolean(),
  modelCalled: z.boolean(),
  at: IsoTimestamp,
  identifiedAt: IsoTimestamp.nullable(),
})
export type ScanRecognitionScan = z.infer<typeof ScanRecognitionScan>

/** One row of the user-facing view `scan_recognition.v_user_scans`: the user's own scans. */
export const ScanRecognitionUserScan = z.strictObject({
  id: Uuid,
  method: ScanRecognitionMethod,
  status: ScanRecognitionStatus,
  identified: ProductCatalogueId.nullable(),
  candidates: z.array(ProductCatalogueId),
  confidence: z.number().min(0).max(1).nullable(),
  confirmed: z.boolean(),
  searchPhrases: z.array(z.string()),
  at: IsoTimestamp,
})
export type ScanRecognitionUserScan = z.infer<typeof ScanRecognitionUserScan>

/** Error codes returned as values (rule 3 of docs/design/modules/_rules.md). */
export const ScanRecognitionErrorCode = z.enum([
  'scan-recognition.off', //                 the module is off: scan mode is unavailable
  'scan-recognition.invalid_input', //       the scan form or confirmation failed its schema
  'scan-recognition.account_restricted', //  the account is suspended or banned
  'scan-recognition.cap_reached', //         the user's scan spend would pass SCAN_SPEND_CAP_MINOR
  'scan-recognition.paid_work_paused', //    cost-meter or the model provider is off: fail closed
  'scan-recognition.unknown_model', //       no price for the vision model: never spend unpriced
  'scan-recognition.model_failed', //        the model call threw; nothing written
  'scan-recognition.not_found', //           no such scan for this user
  'scan-recognition.not_a_candidate', //     the confirmed ID is not one of the scan's candidates
  'scan-recognition.conflict', //            the scan ID exists with different input
])
export type ScanRecognitionErrorCode = z.infer<typeof ScanRecognitionErrorCode>

export const ScanRecognitionError = z.strictObject({
  code: ScanRecognitionErrorCode,
  message: z.string().min(1),
})
export type ScanRecognitionError = z.infer<typeof ScanRecognitionError>

/** The payload of `scan-recognition.identified`: the scan ID only (rule 7). */
export const ScanRecognitionIdentifiedEvent = z.strictObject({ scanId: Uuid })
export type ScanRecognitionIdentifiedEvent = z.infer<typeof ScanRecognitionIdentifiedEvent>

/** Events this module publishes. A breaking payload change adds a version (README.md). */
export const events = defineEvents(module, {
  /** A scan was identified, by barcode, by the model at or above the threshold, or by the user. */
  'scan-recognition.identified': { 1: ScanRecognitionIdentifiedEvent },
})
