import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterEach, describe, expect, it } from 'vitest'
import { scaffoldModule, validateName } from '../../../scripts/new-module.mjs'
import { plan } from '../scripts/migrate.mjs'
import { repoRoot } from './paths'

// Proves `pnpm new:module` on a throwaway module in a temporary copy of the tree; nothing is
// written to the repository. CI also scaffolds a probe module end to end (typecheck, tests,
// db:generate, dry-run): .github/workflows/ci.yml, job "Migration dry-run".

const roots: string[] = []
afterEach(() => {
  for (const root of roots.splice(0)) rmSync(root, { recursive: true, force: true })
})

function tempRoot(): string {
  const root = mkdtempSync(join(tmpdir(), 'nabvy-scaffold-'))
  roots.push(root)
  // scaffoldModule reads services/usage-ledger/package.json for the reference dependency set
  // (the merged shape task 0.13 was told to match), so the temp root needs a copy of it.
  mkdirSync(join(root, 'services', 'usage-ledger'), { recursive: true })
  writeFileSync(
    join(root, 'services', 'usage-ledger', 'package.json'),
    readFileSync(join(repoRoot, 'services', 'usage-ledger', 'package.json')),
  )
  return root
}

const GENERATED_MARKER = 'generated by scripts/new-module.mjs; edit freely'

describe('pnpm new:module', () => {
  it('creates the module in the merged shape, its contracts, config, schema and migrations home', () => {
    const root = tempRoot()
    const written = scaffoldModule({ root, name: 'throwaway-probe' })
    for (const path of [
      'services/throwaway-probe/README.md',
      'services/throwaway-probe/package.json',
      'services/throwaway-probe/tsconfig.json',
      'services/throwaway-probe/vitest.config.ts',
      'services/throwaway-probe/src/index.ts',
      'services/throwaway-probe/src/handlers/index.ts',
      'services/throwaway-probe/src/domain/index.ts',
      'services/throwaway-probe/src/repo/index.ts',
      'services/throwaway-probe/test/support/database.ts',
      'services/throwaway-probe/test/switch.test.ts',
      'services/throwaway-probe/test/idempotency.test.ts',
      'services/throwaway-probe/test/contracts.test.ts',
      'packages/contracts/src/modules/throwaway-probe.ts',
      'packages/config/src/modules/throwaway-probe.ts',
      'packages/db/src/schema/throwaway-probe.ts',
      'packages/db/migrations/throwaway-probe/module.json',
      'packages/db/migrations/throwaway-probe/drizzle.config.ts',
      'packages/db/tests/throwaway-probe.test.sql',
    ]) {
      expect(written).toContain(path)
      expect(existsSync(join(root, path)), path).toBe(true)
    }

    const readme = readFileSync(join(root, 'services/throwaway-probe/README.md'), 'utf8')
    for (const section of [
      'Switch and priority',
      'Inputs',
      'Outputs',
      'Tables',
      'Rules and thresholds',
      'Fixtures and pass rate',
      'Decisions',
      'Open questions',
      'Incidents',
    ]) {
      expect(readme).toContain(`\n## ${section}\n`)
    }
    expect(readme).toContain(GENERATED_MARKER)

    const pkg = JSON.parse(
      readFileSync(join(root, 'services/throwaway-probe/package.json'), 'utf8'),
    )
    expect(pkg.name).toBe('@nabvy/throwaway-probe')
    const usageLedgerPkg = JSON.parse(
      readFileSync(join(root, 'services/usage-ledger/package.json'), 'utf8'),
    )
    expect(pkg.dependencies).toEqual(usageLedgerPkg.dependencies)
    expect(pkg.devDependencies).toEqual(usageLedgerPkg.devDependencies)

    const vitestConfig = readFileSync(
      join(root, 'services/throwaway-probe/vitest.config.ts'),
      'utf8',
    )
    expect(vitestConfig).toContain('hookTimeout: 60000')
    expect(vitestConfig).toContain('testTimeout: 30000')

    expect(readFileSync(join(root, 'packages/db/src/schema/throwaway-probe.ts'), 'utf8')).toContain(
      "moduleSchema('throwaway-probe')",
    )

    const manifest = JSON.parse(
      readFileSync(join(root, 'packages/db/migrations/throwaway-probe/module.json'), 'utf8'),
    )
    expect(manifest).toEqual({
      module: 'throwaway-probe',
      schema: 'throwaway_probe',
      dependsOn: ['core'],
    })

    // Every generated file that can carry a comment does; JSON has no comment syntax.
    for (const path of written) {
      if (path.endsWith('.json')) continue
      expect(readFileSync(join(root, path), 'utf8'), path).toContain(GENERATED_MARKER)
    }
  })

  it('takes dependsOn from the caller (--depends-on)', () => {
    const root = tempRoot()
    scaffoldModule({ root, name: 'throwaway-probe', dependsOn: ['core', 'switches'] })
    const manifest = JSON.parse(
      readFileSync(join(root, 'packages/db/migrations/throwaway-probe/module.json'), 'utf8'),
    )
    expect(manifest.dependsOn).toEqual(['core', 'switches'])
  })

  it('produces a migrations home the runner accepts', () => {
    const root = tempRoot()
    scaffoldModule({ root, name: 'throwaway-probe' })
    const dir = join(root, 'packages/db/migrations')
    mkdirSync(join(dir, 'core'))
    writeFileSync(join(dir, 'core', 'module.json'), '{"module":"core","schema":"nabvy_core"}')
    writeFileSync(join(dir, 'throwaway-probe', '20260924000000_throwaway_probe.sql'), 'select 1;')
    expect(plan(dir).map((m) => m.module)).toEqual(['throwaway-probe'])
  })

  it('refuses to overwrite a module and refuses bad or reserved names', () => {
    const root = tempRoot()
    scaffoldModule({ root, name: 'throwaway-probe' })
    expect(() => scaffoldModule({ root, name: 'throwaway-probe' })).toThrow(/already exists/)
    for (const name of [undefined, 'Bad_Name', 'auth', 'storage', 'core', 'db', 'nabvy-core']) {
      expect(() => validateName(name)).toThrow()
    }
    expect(validateName('copy-advert-spam')).toBe('copy_advert_spam')
  })
})
