// generated by scripts/new-module.mjs; edit freely
// Drizzle Kit configuration for the asking-price-position module's migrations. Paths are relative to
// packages/db, where `pnpm db:generate asking-price-position` runs. See packages/db/README.md.
import { defineConfig } from 'drizzle-kit'

export default defineConfig({
  dialect: 'postgresql',
  schema: './src/schema/asking-price-position.ts',
  out: './migrations/asking-price-position',
  schemaFilter: ['asking_price_position'],
  migrations: { prefix: 'supabase' },
})
